/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import javax.swing.JOptionPane;
import logica.Temperaturas;

/**
 *
 * @author Leonel Amaya
 */
public class Temperatura extends javax.swing.JFrame {

    /**
     * Creates new form Temperatura
     */
    public Temperatura() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Conversor Temperaturas");
        initCombo1();
        initCombo2();
    }
    
    private void initCombo1(){
        opcionTemp.addItem("Celsius");
        opcionTemp.addItem("Kelvin");
        opcionTemp.addItem("Fahrenheit");
    }
    
    private void initCombo2(){
        opcionTemp2.addItem("Celsius");
        opcionTemp2.addItem("Kelvin");
        opcionTemp2.addItem("Fahrenheit");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cantidad = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        opcionTemp = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        opcionTemp2 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        resul3 = new javax.swing.JTextArea();
        convertir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantidad.setBorder(null);
        jPanel1.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 160, 40));

        jSeparator1.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 180, 20));

        opcionTemp.setBorder(null);
        jPanel1.add(opcionTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 140, 40));

        jButton1.setBackground(new java.awt.Color(55, 75, 92));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Volver");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 80, 30));

        opcionTemp2.setBorder(null);
        jPanel1.add(opcionTemp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 140, 40));

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setOpaque(true);

        resul3.setColumns(20);
        resul3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        resul3.setRows(5);
        resul3.setOpaque(true);
        jScrollPane3.setViewportView(resul3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 190, 70));

        convertir.setBackground(new java.awt.Color(227, 141, 116));
        convertir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        convertir.setForeground(new java.awt.Color(255, 255, 255));
        convertir.setText("Convertir");
        convertir.setBorder(null);
        convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirActionPerformed(evt);
            }
        });
        jPanel1.add(convertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/calido.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Bienvenida inicio = new Bienvenida();
        inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void convertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirActionPerformed
        Temperaturas temperaturas = new Temperaturas();
        
        try {
            double valor = Double.parseDouble(cantidad.getText());
            temperaturas.setTemperatura(valor);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Solo pueden ser valor númericos");
        }
        
        String temperatura1 = opcionTemp.getSelectedItem().toString();
        String temperatura2 = opcionTemp2.getSelectedItem().toString();
        
        temperaturas.setTemp1(temperatura1);
        temperaturas.setTemp2(temperatura2);
        
        double temperaturaConvertida = temperaturas.Transformar();
        
        resul3.setText("");
        resul3.append(temperaturaConvertida + " " + temperaturas.getTemp2());
    }//GEN-LAST:event_convertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Temperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Temperatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidad;
    private javax.swing.JButton convertir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> opcionTemp;
    private javax.swing.JComboBox<String> opcionTemp2;
    private javax.swing.JTextArea resul3;
    // End of variables declaration//GEN-END:variables
}
